### ISSUE TITLE
Shields.io 뱃지 추가

### ISSUE THREAD

**Issue by antop-dev** [antop-dev/billiards-love#37]
https://shields.io/

1. README.md 에 뱃지를 추가한다.
2. 라이선스 파일을 추가한다.

**Comment by Jammini** [comment]
![image](https://user-images.githubusercontent.com/59176149/93075986-9957a380-f6c1-11ea-8a74-41d2561b04c0.png)
이게 뱃지 인가요?

**Comment by antop-dev** [comment]
네 그건 `SonarQube` 관련된 뱃지인데 프로젝트가 두개로 분리되면서 현재 `README.md` 에 있는 뱃지는 에러가 나는 상태입니다.

https://github.com/antop-dev/billiards-love/pull/39 머지되면 정상 출력될 예정입니다.

**Comment by antop-dev** [comment]
현재 뱃지를 추가하면 예상되는 내용은 아래와 같습니다.

![image](https://user-images.githubusercontent.com/25427395/93077227-7af2a780-f6c3-11ea-81f1-1a412cf75b43.png)
