### ISSUE TITLE
JPA Entity, Repository 작성 - 2차

### ISSUE THREAD

**Issue by antop-dev** [antop-dev/billiards-love#40]
1. 테스트 메소드 네이밍
1. `Entity` 테스트 코드 추가
2. `Repository` 테스트 시 스텁<sup>`SQL`</sup> 기반으로 테스트 코드 작성

* https://www.baeldung.com/spring-boot-data-sql-and-schema-sql

**Comment by Jammini** [comment]
스텁을 통해 연관관계 데이터들이 이미 존재하는 거처럼 데이터를 집어넣고 테스트 코드를 작성하라는거 맞나요?

**Comment by antop-dev** [comment]
넹 `SQL` 파일을 만들어서 테스트 하기전 미리 데이터 맞춰 놓으려고 `SQL` 파일 준비중 입니다.
